SistemaEventos/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaEventos.Models;
using X.PagedList;

namespace SistemaEventos.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ContextoDeDatos contexto;
        public CategoriaController(ContextoDeDatos contexto)
        {
            this.contexto = contexto;
        }
        // accion que muestra la pagina principal
        public  async  Task<IActionResult> Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var categoria = await contexto.Categorias.OrderBy(c => c.Nombre).ToPagedListAsync(pageNumber, pageSize);
            return View(categoria);
        }

        // accion que muestra los datos 
        public async Task<IActionResult> Details(int id)
        {
            var categoria = await contexto.Categorias.SingleOrDefaultAsync(c => c.Id == id);
           
            return View(categoria);
        }

        // muestra el formulario de crear
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoriaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                contexto.Categorias.Add(categoria);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(categoria);
        }

        // GET: CategoriaController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var categoria = await contexto.Categorias.SingleOrDefaultAsync(c => c.Id == id);
            return View(categoria);
        }

        // POST: CategoriaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                var temp = await contexto.Categorias.SingleOrDefaultAsync(c => c.Id == categoria.Id);
                temp.Nombre = categoria.Nombre;
                temp.DescripcionCategoria = categoria.DescripcionCategoria;

                contexto.Categorias.Update(temp);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(categoria);
        }

        // metodo que muestra el formulario para eliminar un registro
        public async Task<IActionResult> Delete(int id)
        {
            var categoria = await contexto.Categorias.SingleOrDefaultAsync(c => c.Id == id);
            return View(categoria);
        }

        // metodo que recibe los datos y los elimina
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> Delete(int id, Categoria categoria)
        {
            var temp = await contexto.Categorias.SingleOrDefaultAsync(c => c.Id == categoria.Id);

            if (temp != null)
            {
                contexto.Categorias.Remove(temp);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(temp);
        }

}
}

SistemaEventos/Controllers/EventoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaEventos.Models;
using X.PagedList;

namespace SistemaEventos.Controllers
{
    public class EventoController : Controller
    {
        private readonly ContextoDeDatos contexto;

        public EventoController(ContextoDeDatos contexto)
        {
            this.contexto = contexto;
        }
        // GET: EventoController
        public  async Task<IActionResult> Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var eventos = await contexto.Eventos.OrderBy(e => e.NombreEvento).ToPagedListAsync(pageNumber, pageSize);
            return View(eventos);
        }
        public async Task<IActionResult> IndexUsuario(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var eventos = await contexto.Eventos.OrderBy(e => e.NombreEvento).ToPagedListAsync(pageNumber, pageSize);
            return View(eventos);
        }

        // GET: EventoController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var eventos = await contexto.Eventos.SingleOrDefaultAsync(e => e.Id == id);
            return View(eventos);
        }

        // GET: EventoController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EventoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Evento evento)
        {
            if (ModelState.IsValid)
            {
                contexto.Eventos.Add(evento);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(evento);
        }

        // GET: EventoController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var evento = await contexto.Eventos.SingleOrDefaultAsync(e => e.Id == id);
            return View(evento);
        }

        // POST: EventoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Evento evento)
        {
            if (ModelState.IsValid)
            {
                var temp = await contexto.Eventos.SingleOrDefaultAsync(e => e.Id == evento.Id);
                temp.NombreEvento = evento.NombreEvento;
                temp.DescripcionDelEvento = evento.DescripcionDelEvento;
                temp.FechaDelEvento = evento.FechaDelEvento;
                temp.Ubicacion = evento.Ubicacion;

                contexto.Eventos.Update(temp);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(evento);
        }

        // GET: EventoController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var evento = await contexto.Eventos.SingleOrDefaultAsync(e => e.Id == id);
            return View(evento);
        }

        // POST: EventoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Evento evento)
        {
            var temp = await contexto.Eventos.SingleOrDefaultAsync(e => e.Id == id);

            if (temp != null)
            {
                contexto.Eventos.Remove(temp);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(temp);

        }
    }
}

SistemaEventos/Controllers/RegistroEventoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaEventos.Models;
using System.Drawing.Printing;
using System.Linq;
using X.PagedList;

namespace SistemaEventos.Controllers
{
    public class RegistroEventoController : Controller
    {
        private readonly ContextoDeDatos contexto;
        public RegistroEventoController(ContextoDeDatos contexto)
        {
            this.contexto = contexto;
        }
        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 10; //numero de paginas
            int pageNumber = (page ?? 1); //pagina actual

            var registros = await contexto.RegistroEventos
            .Include(r => r.Evento)
            .Include(r => r.Participante)
            .OrderByDescending(r => r.Id) // Ordena los registros por ID (opcional)
            .ToPagedListAsync(pageNumber, pageSize);

            return View(registros);
        }
        public async Task<IActionResult> Details(int id)
        {
            // Busca el registro específico por Id e incluye las entidades relacionadas.
            var registro = await contexto.RegistroEventos
        .Include(r => r.Evento)
        .Include(r => r.Participante)
        .FirstOrDefaultAsync(r => r.Id == id);

            // Verifica si se encontró el registro.
            if (registro == null)
            {
                return NotFound(); // Retorna una vista 404 si no se encuentra el registro.
            }

            return View(registro); // Pasa el registro a la vista.
        }

        
    }
}

SistemaEventos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaEventos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaEventos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaEventos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Evento" asp-action="IndexUsuario">Eventos</a>
                            </li>
                            @if (User.IsInRole("Organizador"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Evento" asp-action="Index">Eventos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="RegistroEvento" asp-action="Index">Ver registros</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
                                </li>
                            }
                            
                            <li class="nav-item">
                                <form asp-controller="Usuario" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Cerrar sesión</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Iniciar sesión</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Register">Registrar</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SistemaEventos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>