SistemaEventos/Models/Evento.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaEventos.Models
{
    public class Evento
    {
        [Key] 
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es requerido")]
        [MaxLength(50, ErrorMessage = "Maximo 50 caracteres")]
        [Display(Name = "Nombre del evento ")]

        public string NombreEvento { get; set; } = string.Empty;

        [Required(ErrorMessage = "La descripcion es requerida")]
        [MaxLength(400, ErrorMessage = "Maximo 400 caracteres")]
        [Display(Name = "Descripcion del evento ")]
        public string DescripcionDelEvento { get; set; } = string.Empty;

        [Required(ErrorMessage = "La fecha es requerida")]
        [Display(Name = "Fecha del Evento ")]
        public DateOnly FechaDelEvento { get; set; }

        [Required(ErrorMessage = "La ubicacion es requerida")]
        [MaxLength(100, ErrorMessage = "Maximo 50 caracteres")]
        [Display(Name = "Ubicacion del evento ")]
        public string Ubicacion { get; set; } = string.Empty;

        //propiedad de navegacion
        public List<RegistroEvento>? RegistroEventos { get; set; }
   

    }
}

SistemaEventos/Controllers/EventoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaEventos.Models;
using X.PagedList;

namespace SistemaEventos.Controllers
{
    public class EventoController : Controller
    {
        private readonly ContextoDeDatos contexto;

        public EventoController(ContextoDeDatos contexto)
        {
            this.contexto = contexto;
        }
        // GET: EventoController
        public  async Task<IActionResult> Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var eventos = await contexto.Eventos.OrderBy(e => e.NombreEvento).ToPagedListAsync(pageNumber, pageSize);
            return View(eventos);
        }
        public async Task<IActionResult> IndexUsuario(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var eventos = await contexto.Eventos.OrderBy(e => e.NombreEvento).ToPagedListAsync(pageNumber, pageSize);
            return View(eventos);
        }

        // GET: EventoController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var eventos = await contexto.Eventos.SingleOrDefaultAsync(e => e.Id == id);
            return View(eventos);
        }

        // GET: EventoController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EventoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Evento evento)
        {
            if (ModelState.IsValid)
            {
                contexto.Eventos.Add(evento);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(evento);
        }

        // GET: EventoController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var evento = await contexto.Eventos.SingleOrDefaultAsync(e => e.Id == id);
            return View(evento);
        }

        // POST: EventoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Evento evento)
        {
            if (ModelState.IsValid)
            {
                var temp = await contexto.Eventos.SingleOrDefaultAsync(e => e.Id == evento.Id);
                temp.NombreEvento = evento.NombreEvento;
                temp.DescripcionDelEvento = evento.DescripcionDelEvento;
                temp.FechaDelEvento = evento.FechaDelEvento;
                temp.Ubicacion = evento.Ubicacion;

                contexto.Eventos.Update(temp);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(evento);
        }

        // GET: EventoController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var evento = await contexto.Eventos.SingleOrDefaultAsync(e => e.Id == id);
            return View(evento);
        }

        // POST: EventoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Evento evento)
        {
            var temp = await contexto.Eventos.SingleOrDefaultAsync(e => e.Id == id);

            if (temp != null)
            {
                contexto.Eventos.Remove(temp);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(temp);

        }
    }
}

SistemaEventos/Controllers/ParticipanteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaEventos.Models;
using X.PagedList;

namespace SistemaEventos.Controllers
{
    public class ParticipanteController : Controller
    {
        private readonly ContextoDeDatos contexto;
        public ParticipanteController(ContextoDeDatos contexto)
        {
            this.contexto = contexto;
        }
        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 10; //numero de paginas
            int pageNumber = (page ?? 1); //pagina actual

            var participantes = await contexto.Participantes.OrderByDescending(p => p.Id).ToPagedListAsync(pageNumber, pageSize);
            return View(participantes);
        }

        public async Task<IActionResult> Details(int id)
        {
            var participante = await contexto.Participantes.SingleOrDefaultAsync(p => p.Id == id);

            return View(participante);
        }


        //Formulario
        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Participante participante)
        {

            if (ModelState.IsValid)
            {
                contexto.Participantes.Add(participante);
                await contexto.SaveChangesAsync();
                TempData["SuccessMessage"] = "Inscripción exitosa";
                return RedirectToAction("IndexUsuario", "Evento");
            }
            else
                return View(participante);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var participante = await contexto.Participantes.SingleOrDefaultAsync(p => p.Id == id);
            return View(participante);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Participante participante)
        {
            if (ModelState.IsValid)
            {
                var tem = await contexto.Participantes.SingleOrDefaultAsync(p => p.Id == participante.Id);
                tem.Nombre = participante.Nombre;
                tem.Apellido = participante.Apellido;
                tem.Email = participante.Email;
                tem.Telefono = participante.Telefono;

                contexto.Participantes.Update(tem);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(participante);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var participante = await contexto.Participantes.SingleOrDefaultAsync(p => p.Id == id);
            return View(participante);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Participante participante)
        {
            var tem = await contexto.Participantes.SingleOrDefaultAsync(p => p.Id == participante.Id);

            if (tem != null)
            {
                contexto.Participantes.Remove(tem);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
                return View(tem);
        }
    }
}

SistemaEventos/Views/Evento/Create.cshtml
@model SistemaEventos.Models.Evento

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Evento</h1>

<h4>Evento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreEvento" class="control-label"></label>
                <input asp-for="NombreEvento" class="form-control" />
                <span asp-validation-for="NombreEvento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescripcionDelEvento" class="control-label"></label>
                <input asp-for="DescripcionDelEvento" class="form-control" />
                <span asp-validation-for="DescripcionDelEvento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDelEvento" class="control-label"></label>
                <input asp-for="FechaDelEvento" class="form-control" />
                <span asp-validation-for="FechaDelEvento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ubicacion" class="control-label"></label>
                <input asp-for="Ubicacion" class="form-control" />
                <span asp-validation-for="Ubicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaEventos/Views/Evento/Delete.cshtml
@model SistemaEventos.Models.Evento

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<div>
    <h4>Evento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreEvento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreEvento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescripcionDelEvento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescripcionDelEvento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar</a>
    </form>
</div>

SistemaEventos/Views/Evento/Details.cshtml
@model SistemaEventos.Models.Evento

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles del Evento</h1>

<div>
    <h4>Eventos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreEvento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreEvento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescripcionDelEvento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescripcionDelEvento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDelEvento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDelEvento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Regresar</a>
</div>

SistemaEventos/Views/Evento/Edit.cshtml
@model SistemaEventos.Models.Evento

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreEvento" class="control-label"></label>
                <input asp-for="NombreEvento" class="form-control" />
                <span asp-validation-for="NombreEvento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescripcionDelEvento" class="control-label"></label>
                <input asp-for="DescripcionDelEvento" class="form-control" />
                <span asp-validation-for="DescripcionDelEvento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ubicacion" class="control-label"></label>
                <input asp-for="Ubicacion" class="form-control" />
                <span asp-validation-for="Ubicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDelEvento" class="control-label"></label>
                <input asp-for="FechaDelEvento" type="date" class="form-control" />
                <span asp-validation-for="FechaDelEvento" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaEventos/Views/Evento/Index.cshtml
@model IEnumerable<SistemaEventos.Models.Evento>

@{
    ViewData["Title"] = "Index";
}

<h1>Eventos</h1>

<p>
    <a asp-action="Create">Crear Evento</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreEvento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescripcionDelEvento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDelEvento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ubicacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreEvento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescripcionDelEvento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaDelEvento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ubicacion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SistemaEventos/Views/Evento/IndexUsuario.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core

@model IPagedList<SistemaEventos.Models.Evento>

@{
    ViewData["Title"] = "Inscripcion de eventos";
}

<h1>Inscripcion de eventos</h1>
@if (TempData["SuccessMessage"] != null)
{
    <div id="success-message" class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var message = document.getElementById('success-message');
            if (message) {
                setTimeout(function () {
                    message.style.opacity = 0;
                    setTimeout(function () {
                        message.style.display = 'none';
                    }, 600); 
                }, 5000); 
            }
        });
    </script>
}


<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model[0].NombreEvento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].DescripcionDelEvento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Ubicacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.NombreEvento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescripcionDelEvento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ubicacion)
            </td>
            <td>
                    @Html.ActionLink("Inscribirse", "Create", "Participante", null, new { @class = "btn btn-info" })

                    
            </td>
        </tr>
}
    </tbody>
</table>
<div class="text-center">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions
{
    LiElementClasses = new String[] { "page-item" },
    PageClasses = new String[] { "page-link" }
})
</div>

               <br />